### ISSUE TITLE
M1 芯片使用报错

### ISSUE THREAD

**Issue by baker221** [Sitoi/wechat-alipay-merge#2]
Pandas Version: 2.0.2
yaml version: 6.0

报错信息：
```
------------ 开始读取账单 ------------

Traceback (most recent call last):
  File "/Users/xxx/Downloads/wechat-alipay-merge-main/main.py", line 153, in <module>
    main()
  File "/Users/xxx/Downloads/wechat-alipay-merge-main/main.py", line 116, in main
    df_list.append(read_wechat_data(wx_path))
  File "/Users/xxx/Downloads/wechat-alipay-merge-main/main.py", line 31, in read_wechat_data
    wechat_df.iloc[:, 0] = wechat_df.iloc[:, 0].astype("datetime64")
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 116, in _astype_nansafe
    return dta.astype(dtype, copy=False)._ndarray
  File "/opt/homebrew/anaconda3/envs/me/lib/python3.10/site-packages/pandas/core/arrays/datetimes.py", line 694, in astype
    raise TypeError(
TypeError: Casting to unit-less dtype 'datetime64' is not supported. Pass e.g. 'datetime64[ns]' instead.
```

**Comment by Sitoi** [comment]
pandas~=1.2.5
PyYAML~=5.4.1
用这个版本的呢
